### ISSUE TITLE
Add remote client ip and routing key for resources

### ISSUE THREAD

**Issue by yombo** [rabbitmq/rabbitmq-auth-backend-http#15]
First, thanks for this great plugin.  I don't know erlang and trying to figure this out:
 How to add the client IP address to the request and for resources, is it possible to get the routing key?

I want to restrict access by routing key and I'd like to capture the client ip as well. Thanks.

**Comment by michaelklishin** [comment]
Routing key is only present on a few AMQP 0-9-1 methods, namely `queue.(un)bind` and `basic.publish`.

This kind of decision making does not belong to this plugin. Rather, it should be a separate mechanism, e.g. there is a plugin for [source IP range](https://github.com/gotthardp/rabbitmq-auth-backend-ip-range)-based authentication.

You can limit access to specific exchanges, and make your apps use more of those instead of routing key.
