### ISSUE TITLE
Django Rest Framework + auth backend+ RabbitMQ 

### ISSUE THREAD

**Issue by folt** [rabbitmq/rabbitmq-auth-backend-http#50]
I build my application using the django rest framework.
How can I customize the data format that RabbitMQ expects?
The fact is that the django rest framework defines json and the Content-Type: application / json header.
RabbitMQ does not understand the body of the answer.
What do i do?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes we have a certain amount of information to work with. Questions, investigations, root cause analysis, discussions for potential features are all considered to be mailing list material by our team. When/if we have enough details and evidence we'd be happy to file a new issue.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users). Thank you.

**Comment by michaelklishin** [comment]
You can't customise what RabbitMQ expects. It is definitely possible to respond with a content type and payload in any other format. Heck, we've had [a Django-based example](https://github.com/rabbitmq/rabbitmq-auth-backend-http/tree/master/examples/rabbitmq_auth_backend_django) for years — have you seen it?

**Comment by folt** [comment]
https://github.com/rabbitmq/rabbitmq-auth-backend-http/blob/master/src/rabbit_auth_backend_http.erl#L141 

As you can see here is the process of parsing the response string.
https://github.com/rabbitmq/rabbitmq-auth-backend-http/blob/master/src/rabbit_auth_backend_http.erl#L159

Django Rest Framework returns json
It would be more logical in the case of the header of the response "Content-Type: application / json header" to expect not a string but json

Such as
{"Permission": "allow administrator"}

**Comment by michaelklishin** [comment]
@folt or you could just add a regular Django view since you are using Django to begin with.

**Comment by michaelklishin** [comment]
I've filed #51 but it's not a priority for our team.

**Comment by folt** [comment]
Thank you

**Comment by folt** [comment]
Jwt support is planned ?
