### ISSUE TITLE
How can i authencation client subcribe to topic with spring security?

### ISSUE THREAD

**Issue by truongvantoan** [rabbitmq/rabbitmq-auth-backend-http#73]
How can i authencation client subcribe to topic with spring security?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
This plugin is not specific to Spring Security. There's a [Spring Boot example](https://github.com/rabbitmq/rabbitmq-auth-backend-http/tree/master/examples/rabbitmq_auth_backend_spring_boot). What'd be the best way to integrate that with Spring Security is a question that's orthogonal to what this plugin does. I suggest posting this to Stack Overflow which is used by the Spring maintainers and community.
