### ISSUE TITLE
User permissions

### ISSUE THREAD

**Issue by farahamawi** [rabbitmq/rabbitmq-auth-backend-http#74]
I started using this plugin, I added a path(endpoint) for user login to rabbitmq, However I need to authorize users (admin user / readonly user) sending user tags along with the response is not enough.

I tried to send http request from my server to rabbitmq to configure user permissions `/api/permissions/${vhost}/${username}` before send 'allow' to the broker.
is there another way to send the permissions with the response?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
See the [resource_path](https://github.com/rabbitmq/rabbitmq-auth-backend-http#resource_path) endpoint and [Access Control doc guide](http://www.rabbitmq.com/access-control.html). Several [example implementations](https://github.com/rabbitmq/rabbitmq-auth-backend-http/tree/master/examples) are also available.

**Comment by michaelklishin** [comment]
[rabbitmq-users thread](https://groups.google.com/forum/#!topic/rabbitmq-users/b-zRTf1A4UQ)
